=== Nowak0/OrzelPrzyleki/dataSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">

    <xs:element name="websiteData" type="websiteDataType"/>

    <xs:complexType name="websiteDataType">
        <xs:all>
            <xs:element name="players" type="playersType"/>
            <xs:element name="sponsors" type="sponsorsType"/>
            <xs:element name="photos">
                <xs:complexType>
                    <xs:sequence>
                        <xs:group ref="imageAndLink"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="playersType">
        <xs:sequence>
            <xs:element name="player" type="playerType" minOccurs="1" maxOccurs="21"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="playerType">
        <xs:sequence>
            <xs:element name="firstName" type="shortStringType" minOccurs="1" maxOccurs="3"/>
            <xs:element name="lastName" type="shortStringType" minOccurs="1" maxOccurs="3"/>
            <xs:element name="birth" type="xs:gYear" minOccurs="1" maxOccurs="1"/>
            <xs:element name="image" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="playerNumber" type="playerNumberType" minOccurs="1" maxOccurs="1"/>
            <xs:group ref="imageAndLink"/>
            <xs:element name="position">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="positionType">
                            <xs:attribute name="starter" use="required">
                                <xs:simpleType>
                                    <xs:restriction base="shortStringType">
                                        <xs:enumeration value="yes"/>
                                        <xs:enumeration value="no"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:attribute>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="cards" minOccurs="1" maxOccurs="1"> 
                <xs:complexType>
                    <xs:complexContent>
                        <xs:extension base="cardType">
                            <xs:attribute name="suspended" use="optional">
                                <xs:simpleType>
                                    <xs:restriction base="shortStringType">
                                        <xs:enumeration value="yes"/>
                                        <xs:enumeration value="no"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:attribute>
                        </xs:extension>
                    </xs:complexContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attributeGroup ref="team"/>
        <xs:attribute name="captain" use="optional" />
    </xs:complexType>

    <xs:attributeGroup name="team">
        <xs:attribute name="team">
            <xs:simpleType>
                <xs:restriction base="shortStringType">
                    <xs:enumeration value="senior"/>
                    <xs:enumeration value="junior"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:attributeGroup>

    <xs:simpleType name="positionType">
        <xs:restriction base="shortStringType">
            <xs:enumeration value="goalkeeper"/>
            <xs:enumeration value="defender"/>
            <xs:enumeration value="midfielder"/>
            <xs:enumeration value="forward"/>
        </xs:restriction>

    </xs:simpleType>

    <xs:complexType name="cardType">
        <xs:choice>
            <xs:sequence>
                <xs:element name="yellow" type="cardNumberType" minOccurs="1" maxOccurs="1">
                </xs:element>
                <xs:element name="red" type="cardNumberType" minOccurs="1" maxOccurs="1">
                </xs:element>
            </xs:sequence>
            <xs:element name="sum" type="xs:unsignedInt"/>
        </xs:choice>
    </xs:complexType>

    <xs:simpleType name="cardNumberType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="15"/>
        </xs:restriction> 
    </xs:simpleType>

    <xs:complexType name="sponsorsType">
        <xs:sequence>
           <xs:element name="sponsor" type="sponsorType" minOccurs="0" maxOccurs="unbounded"/> 
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="sponsorType">
        <xs:sequence>
            <xs:element name="name" type="shortStringType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="residence" type="shortStringType" minOccurs="1" maxOccurs="2"/>
            <xs:element name="link" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="attachmentType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="source" type="xs:anyURI" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:element name="image" type="attachmentType"/>
    <xs:element name="link" type="attachmentType"/>

    <xs:group name="imageAndLink">
        <xs:sequence>
            <xs:element name="image" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="link" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:group>

    <xs:simpleType name="shortStringType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="20"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="longStringType">
        <xs:restriction  base="xs:string">
            <xs:minLength value="20"/>
            <xs:maxLength value="100"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="playerNumberType">
        <xs:restriction base="xs:integer">
            <xs:maxInclusive value="99"/>
            <xs:pattern value="[1-9][0-9]*"/>
        </xs:restriction> 
    </xs:simpleType>
</xs:schema>

=== Nowak0/OrzelPrzyleki/data.xml
<?xml version="1.0" encoding="UTF-8"?>

<websiteData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="dataSchema.xsd">

   <players>
        <player team="senior">
            <firstName>Maciej</firstName>
            <lastName>Nowak</lastName>
            <birth>1987</birth>
            <image source=""/>
            <playerNumber>8</playerNumber>
            <position>defender</position>
            <cards>
                <yellow>13</yellow>
                <red>0</red>
            </cards>
        </player>
   </players>

   <sponsors>
        <sponsor>
            <name>Przyłęki</name>
        </sponsor>
   </sponsors>

   <photos>
        <image source=""></image>
   </photos>

</websiteData>
